name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Hugo Deploy GitHub Pages
      uses: KavitShah1998/starter-academic@master
      env:
        HUGO_VERSION: 0.79.1
        TARGET_REPO: KavitShah1998/KavitShah1998.github.io
        TOKEN: ${{ secrets.MY_REPO_SECRET }}
        CNAME: https://kavitshah1998.github.io

